In [1]:
import numpy as np
import scipy
import pandas as pd
import matplotlib.pyplot as plt
import math
#import statsmodels
import statsmodels.api as sm

/Users/Zeshun/anaconda3/lib/python3.6/site-packages/statsmodels/compat/pandas.py:56: FutureWarning: The pandas.core.datetools module is deprecated and will be removed in a future version. Please use the pandas.tseries module instead.
  from pandas.core import datetools

In [4]:
data = pd.read_excel("NYU_Spring_2019_assignment_4.xlsx")
data.head()

       Month      RF  Mkt-RF     SMB     HML   HML-DEV     RMW     CMA     UMD
0 1963-07-31  0.0027 -0.0039 -0.0047 -0.0083 -0.005923  0.0066 -0.0115  0.0100
1 1963-08-31  0.0025  0.0507 -0.0079  0.0167  0.002805  0.0039 -0.0040  0.0103
2 1963-09-30  0.0027 -0.0157 -0.0048  0.0018  0.002653 -0.0076  0.0024  0.0016
3 1963-10-31  0.0029  0.0253 -0.0129 -0.0010 -0.021129  0.0275 -0.0224  0.0314
4 1963-11-30  0.0027 -0.0085 -0.0084  0.0171  0.009074 -0.0045  0.0222 -0.0075

# Question 2, replicate table 2

In [9]:
data1 = data.copy()
# make a copy and only modify data1, not the original data
data1 = data1[data1["Month"]>pd.to_datetime("7/01/1963")]
data1 = data1[data1["Month"]<pd.to_datetime("1/01/2014")]
data1.head()

       Month      RF  Mkt-RF     SMB     HML   HML-DEV     RMW     CMA     UMD
0 1963-07-31  0.0027 -0.0039 -0.0047 -0.0083 -0.005923  0.0066 -0.0115  0.0100
1 1963-08-31  0.0025  0.0507 -0.0079  0.0167  0.002805  0.0039 -0.0040  0.0103
2 1963-09-30  0.0027 -0.0157 -0.0048  0.0018  0.002653 -0.0076  0.0024  0.0016
3 1963-10-31  0.0029  0.0253 -0.0129 -0.0010 -0.021129  0.0275 -0.0224  0.0314
4 1963-11-30  0.0027 -0.0085 -0.0084  0.0171  0.009074 -0.0045  0.0222 -0.0075

In [11]:
data1 = sm.add_constant(data1)
# should build six OLS models
# RM-RF ~ SMB + HML + RMW + CMA + UMD
# SMB ~ RM-RF + HML + RMW + CMA + UMD
# HML ~ RM-RF + SMB + RMW + CMA + UMD
# RMW ~ RM-RF + SMB + HML + CMA + UMD
# CMA ~ RM-RF + SMB + HML + RMW + UMD
# UMD ~ RM-RF + SMB + HML + RMW + CMA


X1 = ['const','SMB', 'HML', 'RMW', 'CMA', 'UMD']
X2 = ['const','Mkt-RF', 'HML', 'RMW','CMA', 'UMD']
X3 = ['const','Mkt-RF', 'SMB', 'RMW', 'CMA', 'UMD']
X4 = ['const','Mkt-RF', 'SMB', 'HML','CMA', 'UMD']
X5 = ['const','Mkt-RF', 'SMB', 'HML','RMW', 'UMD']
X6 = ['const','Mkt-RF', 'SMB', 'HML' ,'RMW', 'CMA']
reg1 = sm.OLS(endog=data1['Mkt-RF'], exog=data1[X1]).fit()
reg2 = sm.OLS(endog=data1['SMB'], exog=data1[X2]).fit()
reg3 = sm.OLS(endog=data1['HML'], exog=data1[X3]).fit()
reg4 = sm.OLS(endog=data1['RMW'], exog=data1[X4]).fit()
reg5 = sm.OLS(endog=data1['CMA'], exog=data1[X5]).fit()
reg6 = sm.OLS(endog=data1['UMD'], exog=data1[X6]).fit()

# intialize an 2D matrix with nan
display_mat = np.empty((6,8))
display_mat[:] = np.nan
display_df = pd.DataFrame(display_mat)
display_df.columns = ['const', 'Mkt-RF','SMB', 'HML', 'RMW', 'CMA', 'UMD', r'$R^2$']
display_df.index = ['Mkt-RF','SMB', 'HML', 'RMW', 'CMA', 'UMD']

display_df.loc[['Mkt-RF'],['const','SMB', 'HML', 'RMW', 'CMA', 'UMD',r'$R^2$']] = np.append(np.array(reg1.params), reg1.rsquared)
display_df.loc[['SMB'],['const','Mkt-RF', 'HML', 'RMW','CMA', 'UMD',r'$R^2$']]  = np.append(np.array(reg2.params), reg2.rsquared)
display_df.loc[['HML'],['const','Mkt-RF', 'SMB', 'RMW', 'CMA', 'UMD',r'$R^2$']] = np.append(np.array(reg3.params), reg3.rsquared)
display_df.loc[['RMW'],['const','Mkt-RF', 'SMB', 'HML','CMA', 'UMD',r'$R^2$']]  = np.append(np.array(reg4.params), reg4.rsquared)
display_df.loc[['CMA'],['const','Mkt-RF', 'SMB', 'HML','RMW', 'UMD',r'$R^2$']]  = np.append(np.array(reg5.params), reg5.rsquared)
display_df.loc[['UMD'],['const','Mkt-RF', 'SMB', 'HML' ,'RMW', 'CMA',r'$R^2$']] = np.append(np.array(reg6.params), reg6.rsquared)


# since in the table 2 from the paper, intercepts are given in an annual basis
# simply multiply the data by 12 
display_df['const'] *=12
display_df

,const,Mkt-RF,SMB,HML,RMW,CMA,UMD,$R^2$
Mkt-RF,0.105657,NaN,0.242051,0.021310,-0.378907,-0.863485,-0.102939,0.251775
SMB,0.040937,0.125416,NaN,0.059996,-0.432065,-0.152580,0.035377,0.164742
HML,0.009849,0.005348,0.029061,NaN,0.166068,0.988911,-0.119684,0.528258
RMW,0.046042,-0.099929,-0.219919,0.174507,NaN,-0.350179,0.067163,0.196686
CMA,0.026635,-0.103562,-0.035318,0.472574,-0.159249,NaN,0.047043,0.563081
UMD,0.085779,-0.112616,0.074694,-0.521698,0.278604,0.429109,NaN,0.089382

In [12]:
reg1.params

const    0.008805
SMB      0.242051
HML      0.021310
RMW     -0.378907
CMA     -0.863485
UMD     -0.102939
dtype: float64

# Question 3

Not exactly. Maybe raw data were not cleaned in the same way.

# Question 4, replicate table 4

In [13]:
# should build six OLS models
# RM-RF ~ SMB + HML-DEV + RMW + CMA + UMD
# SMB ~ RM-RF + HML-DEV + RMW + CMA + UMD
# HML-DEV ~ RM-RF + SMB + RMW + CMA + UMD
# RMW ~ RM-RF + SMB + HML-DEV + CMA + UMD
# CMA ~ RM-RF + SMB + HML-DEV + RMW + UMD
# UMD ~ RM-RF + SMB + HML-DEV + RMW + CMA


X1 = ['const','SMB', 'HML-DEV', 'RMW', 'CMA', 'UMD']
X2 = ['const','Mkt-RF', 'HML-DEV', 'RMW','CMA', 'UMD']
X3 = ['const','Mkt-RF', 'SMB', 'RMW', 'CMA', 'UMD']
X4 = ['const','Mkt-RF', 'SMB', 'HML-DEV','CMA', 'UMD']
X5 = ['const','Mkt-RF', 'SMB', 'HML-DEV','RMW', 'UMD']
X6 = ['const','Mkt-RF', 'SMB', 'HML-DEV' ,'RMW', 'CMA']
reg1 = sm.OLS(endog=data1['Mkt-RF'], exog=data1[X1]).fit()
reg2 = sm.OLS(endog=data1['SMB'], exog=data1[X2]).fit()
reg3 = sm.OLS(endog=data1['HML-DEV'], exog=data1[X3]).fit()
reg4 = sm.OLS(endog=data1['RMW'], exog=data1[X4]).fit()
reg5 = sm.OLS(endog=data1['CMA'], exog=data1[X5]).fit()
reg6 = sm.OLS(endog=data1['UMD'], exog=data1[X6]).fit()

# intialize an 2D matrix with nan
display_mat = np.empty((6,8))
display_mat[:] = np.nan
display_df = pd.DataFrame(display_mat)
display_df.columns = ['const', 'Mkt-RF','SMB', 'HML-DEV', 'RMW', 'CMA', 'UMD', r'$R^2$']
display_df.index = ['Mkt-RF','SMB', 'HML-DEV', 'RMW', 'CMA', 'UMD']

display_df.loc[['Mkt-RF'],['const','SMB', 'HML-DEV', 'RMW', 'CMA', 'UMD',r'$R^2$']] = np.append(np.array(reg1.params), reg1.rsquared)
display_df.loc[['SMB'],['const','Mkt-RF', 'HML-DEV', 'RMW','CMA', 'UMD',r'$R^2$']]  = np.append(np.array(reg2.params), reg2.rsquared)
display_df.loc[['HML-DEV'],['const','Mkt-RF', 'SMB', 'RMW', 'CMA', 'UMD',r'$R^2$']] = np.append(np.array(reg3.params), reg3.rsquared)
display_df.loc[['RMW'],['const','Mkt-RF', 'SMB', 'HML-DEV','CMA', 'UMD',r'$R^2$']]  = np.append(np.array(reg4.params), reg4.rsquared)
display_df.loc[['CMA'],['const','Mkt-RF', 'SMB', 'HML-DEV','RMW', 'UMD',r'$R^2$']]  = np.append(np.array(reg5.params), reg5.rsquared)
display_df.loc[['UMD'],['const','Mkt-RF', 'SMB', 'HML-DEV' ,'RMW', 'CMA',r'$R^2$']] = np.append(np.array(reg6.params), reg6.rsquared)

# since in the table 2 from the paper, intercepts are given in an annual basis
# simply multiply the data by 12 
display_df['const'] *=12
display_df

,const,Mkt-RF,SMB,HML-DEV,RMW,CMA,UMD,$R^2$
Mkt-RF,0.107771,NaN,0.244095,-0.039887,-0.373269,-0.807281,-0.126267,0.251988
SMB,0.037729,0.126365,NaN,0.077342,-0.425476,-0.160793,0.068510,0.165707
HML-DEV,0.048494,-0.010001,0.037458,NaN,0.049938,0.874715,-0.521668,0.680981
RMW,0.046436,-0.101136,-0.222685,0.053966,NaN,-0.229620,0.075682,0.174941
CMA,0.012230,-0.107757,-0.041459,0.465686,-0.113122,NaN,0.232345,0.513874
UMD,0.089894,-0.065013,0.068140,-1.071306,0.143821,0.896245,NaN,0.571543

# Question 5

Not exactly. Maybe raw data were not cleaned in the same way.

# Question 6, replicate table 2 & 4 with new data

In [17]:
data2 = data.copy()
data2 = data2[data2["Month"]>pd.to_datetime("1/01/2014")]
data2 = sm.add_constant(data2)
data2.head()

,const,Month,RF,Mkt-RF,SMB,HML,HML-DEV,RMW,CMA,UMD
606,1.0,2014-01-31,0.0,-0.0332,0.0059,-0.0209,-0.008910,-0.0400,-0.0138,0.0172
607,1.0,2014-02-28,0.0,0.0465,0.0013,-0.0040,-0.009422,-0.0024,-0.0044,0.0208
608,1.0,2014-03-31,0.0,0.0043,-0.0117,0.0508,0.034502,0.0215,0.0189,-0.0330
609,1.0,2014-04-30,0.0,-0.0019,-0.0417,0.0114,0.024357,0.0351,0.0105,-0.0385
610,1.0,2014-05-31,0.0,0.0206,-0.0189,-0.0027,-0.004299,0.0009,-0.0106,0.0115

In [22]:
# should build six OLS models
# RM-RF ~ SMB + HML + RMW + CMA + UMD
# SMB ~ RM-RF + HML + RMW + CMA + UMD
# HML ~ RM-RF + SMB + RMW + CMA + UMD
# RMW ~ RM-RF + SMB + HML + CMA + UMD
# CMA ~ RM-RF + SMB + HML + RMW + UMD
# UMD ~ RM-RF + SMB + HML + RMW + CMA


X1 = ['const','SMB', 'HML', 'RMW', 'CMA', 'UMD']
#X1 = sm.add_constant(X1)
X2 = ['const','Mkt-RF', 'HML', 'RMW','CMA', 'UMD']
X3 = ['const','Mkt-RF', 'SMB', 'RMW', 'CMA', 'UMD']
X4 = ['const','Mkt-RF', 'SMB', 'HML','CMA', 'UMD']
X5 = ['const','Mkt-RF', 'SMB', 'HML','RMW', 'UMD']
X6 = ['const','Mkt-RF', 'SMB', 'HML' ,'RMW', 'CMA']
reg1 = sm.OLS(endog=data2['Mkt-RF'], exog=data2[X1]).fit()
reg2 = sm.OLS(endog=data2['SMB'], exog=data2[X2]).fit()
reg3 = sm.OLS(endog=data2['HML'], exog=data2[X3]).fit()
reg4 = sm.OLS(endog=data2['RMW'], exog=data2[X4]).fit()
reg5 = sm.OLS(endog=data2['CMA'], exog=data2[X5]).fit()
reg6 = sm.OLS(endog=data2['UMD'], exog=data2[X6]).fit()

# intialize an 2D matrix with nan
display_mat = np.empty((6,8))
display_mat[:] = np.nan
display_df = pd.DataFrame(display_mat)
display_df.columns = ['const', 'Mkt-RF','SMB', 'HML', 'RMW', 'CMA', 'UMD', r'$R^2$']
display_df.index = ['Mkt-RF','SMB', 'HML', 'RMW', 'CMA', 'UMD']

display_df.loc[['Mkt-RF'],['const','SMB', 'HML', 'RMW', 'CMA', 'UMD',r'$R^2$']] = np.append(np.array(reg1.params), reg1.rsquared)
display_df.loc[['SMB'],['const','Mkt-RF', 'HML', 'RMW','CMA', 'UMD',r'$R^2$']]  = np.append(np.array(reg2.params), reg2.rsquared)
display_df.loc[['HML'],['const','Mkt-RF', 'SMB', 'RMW', 'CMA', 'UMD',r'$R^2$']] = np.append(np.array(reg3.params), reg3.rsquared)
display_df.loc[['RMW'],['const','Mkt-RF', 'SMB', 'HML','CMA', 'UMD',r'$R^2$']]  = np.append(np.array(reg4.params), reg4.rsquared)
display_df.loc[['CMA'],['const','Mkt-RF', 'SMB', 'HML','RMW', 'UMD',r'$R^2$']]  = np.append(np.array(reg5.params), reg5.rsquared)
display_df.loc[['UMD'],['const','Mkt-RF', 'SMB', 'HML' ,'RMW', 'CMA',r'$R^2$']] = np.append(np.array(reg6.params), reg6.rsquared)

# since in the table 2 from the paper, intercepts are given in an annual basis
# simply multiply the data by 12 
display_df['const'] *=12

## Table 2 with new data

In [23]:
display_df

,const,Mkt-RF,SMB,HML,RMW,CMA,UMD,$R^2$
Mkt-RF,0.075685,NaN,0.335632,-0.063310,0.129398,-0.878282,-0.372682,0.227895
SMB,-0.020178,0.194618,NaN,0.170599,-0.773814,0.127894,-0.017371,0.301490
HML,0.003311,-0.022089,0.102649,NaN,-0.038638,0.830394,-0.189546,0.500380
RMW,0.012979,0.027124,-0.279729,-0.023213,NaN,0.221494,-0.033151,0.258735
CMA,-0.003491,-0.112401,0.028227,0.304592,0.135231,NaN,-0.128957,0.541010
UMD,0.030093,-0.280626,-0.022558,-0.409074,-0.119088,-0.758752,NaN,0.400968

In [27]:
# should build six OLS models
# RM-RF ~ SMB + HML-DEV + RMW + CMA + UMD
# SMB ~ RM-RF + HML-DEV + RMW + CMA + UMD
# HML-DEV ~ RM-RF + SMB + RMW + CMA + UMD
# RMW ~ RM-RF + SMB + HML-DEV + CMA + UMD
# CMA ~ RM-RF + SMB + HML-DEV + RMW + UMD
# UMD ~ RM-RF + SMB + HML-DEV + RMW + CMA


X1 = ['const','SMB', 'HML-DEV', 'RMW', 'CMA', 'UMD']
#X1 = sm.add_constant(X1)
X2 = ['const','Mkt-RF', 'HML-DEV', 'RMW','CMA', 'UMD']
X3 = ['const','Mkt-RF', 'SMB', 'RMW', 'CMA', 'UMD']
X4 = ['const','Mkt-RF', 'SMB', 'HML-DEV','CMA', 'UMD']
X5 = ['const','Mkt-RF', 'SMB', 'HML-DEV','RMW', 'UMD']
X6 = ['const','Mkt-RF', 'SMB', 'HML-DEV' ,'RMW', 'CMA']
reg1 = sm.OLS(endog=data2['Mkt-RF'], exog=data2[X1]).fit()
reg2 = sm.OLS(endog=data2['SMB'], exog=data2[X2]).fit()
reg3 = sm.OLS(endog=data2['HML-DEV'], exog=data2[X3]).fit()
reg4 = sm.OLS(endog=data2['RMW'], exog=data2[X4]).fit()
reg5 = sm.OLS(endog=data2['CMA'], exog=data2[X5]).fit()
reg6 = sm.OLS(endog=data2['UMD'], exog=data2[X6]).fit()

# intialize an 2D matrix with nan
display_mat = np.empty((6,8))
display_mat[:] = np.nan
display_df = pd.DataFrame(display_mat)
display_df.columns = ['const', 'Mkt-RF','SMB', 'HML-DEV', 'RMW', 'CMA', 'UMD', r'$R^2$']
display_df.index = ['Mkt-RF','SMB', 'HML-DEV', 'RMW', 'CMA', 'UMD']

display_df.loc[['Mkt-RF'],['const','SMB', 'HML-DEV', 'RMW', 'CMA', 'UMD',r'$R^2$']] = np.append(np.array(reg1.params), reg1.rsquared)
display_df.loc[['SMB'],['const','Mkt-RF', 'HML-DEV', 'RMW','CMA', 'UMD',r'$R^2$']]  = np.append(np.array(reg2.params), reg2.rsquared)
display_df.loc[['HML-DEV'],['const','Mkt-RF', 'SMB', 'RMW', 'CMA', 'UMD',r'$R^2$']] = np.append(np.array(reg3.params), reg3.rsquared)
display_df.loc[['RMW'],['const','Mkt-RF', 'SMB', 'HML-DEV','CMA', 'UMD',r'$R^2$']]  = np.append(np.array(reg4.params), reg4.rsquared)
display_df.loc[['CMA'],['const','Mkt-RF', 'SMB', 'HML-DEV','RMW', 'UMD',r'$R^2$']]  = np.append(np.array(reg5.params), reg5.rsquared)
display_df.loc[['UMD'],['const','Mkt-RF', 'SMB', 'HML-DEV' ,'RMW', 'CMA',r'$R^2$']] = np.append(np.array(reg6.params), reg6.rsquared)

# since in the table 2 from the paper, intercepts are given in an annual basis
# simply multiply the data by 12 
display_df['const'] *=12

## Table 4 with new data

In [28]:
display_df

,const,Mkt-RF,SMB,HML-DEV,RMW,CMA,UMD,$R^2$
Mkt-RF,0.077078,NaN,0.333310,0.169160,0.183149,-1.055308,-0.269173,0.232436
SMB,-0.020920,0.197279,NaN,-0.084160,-0.817811,0.338171,-0.094912,0.291202
HML-DEV,-0.012095,0.042988,-0.036134,NaN,-0.307875,0.768079,-0.528418,0.743566
RMW,0.009105,0.035832,-0.270324,-0.237025,NaN,0.369683,-0.151925,0.312211
CMA,0.002126,-0.129890,0.070323,0.372012,0.232574,NaN,0.018084,0.561163
UMD,0.005521,-0.116191,-0.069220,-0.897582,-0.335202,0.063422,NaN,0.658618

# Question 7

They don't match the previous tables exactly. Observe that the most obvious differece is that the market delivers lower excess return, which drops from about 10% to 7%.

One possible reason is that under different time periods, the performance of stocks are dominated by different factors, i.e. the "true theoratical" model has changed. Another possible reason is that every regression we do is a biased (w.r.t. time) sample of the theoratical model. It might be that different samples give us different bias.

# Question 8
Yes I would still agree that CMA now seems to be a redundant factor. We can see that the intercept is 0.002, which is still very low. Also, the fact that $R^2$ is large shows that much of this factor can be explained by the combinations of other factors.